--------------------------------------------------------------------------------
-- Creaci�n del Modelo Relacional.
-- Se conecta con el usuario creado para el modelo ER.
--------------------------------------------------------------------------------
CREATE TABLE TIPO_CUENTA (
   TCT_ID          INTEGER NOT NULL CONSTRAINT PK_TCT_ID PRIMARY KEY,
   TCT_DESCRIPCION VARCHAR(30)NOT NULL
);

CREATE TABLE TIPO_CLIENTE (
   TCL_ID          INTEGER NOT NULL CONSTRAINT PK_TCL_ID PRIMARY KEY,
   TCL_DESCRIPCION VARCHAR(30)NOT NULL
);

CREATE TABLE ESTADO_CLIENTE (
   ECT_ID          INTEGER NOT NULL CONSTRAINT PK_ECT_ID PRIMARY KEY,
   ECT_DESCRIPCION VARCHAR(30)NOT NULL
);

CREATE TABLE CLIENTE (
   CTE_ID     INTEGER NOT NULL CONSTRAINT PK_CTE_ID PRIMARY KEY,
   CTE_TCL_ID INTEGER NOT NULL,
   CTE_ECT_ID INTEGER NOT NULL,
   CONSTRAINT CTE_TCL FOREIGN KEY (CTE_TCL_ID)REFERENCES TIPO_CLIENTE(TCL_ID),
   CONSTRAINT FK_CTE_ECL FOREIGN KEY (CTE_ECT_ID)REFERENCES ESTADO_CLIENTE(ECT_ID)
);

CREATE TABLE CUENTA (
   CTA_ID            INTEGER NOT NULL CONSTRAINT PK_CTA_ID PRIMARY KEY,
   CTA_CTE_ID        INTEGER NOT NULL,
   CTA_TCT_ID        INTEGER NOT NULL,
   CTA_NUMERO_CUENTA VARCHAR(20)NOT NULL,
   CONSTRAINT CTA_TCT FOREIGN KEY (CTA_TCT_ID)REFERENCES TIPO_CUENTA(TCT_ID),
   CONSTRAINT FK_CTA_CTE FOREIGN KEY (CTA_CTE_ID)REFERENCES CLIENTE(CTE_ID)
);

CREATE TABLE MOVIMIENTO (
   MVM_ID     INTEGER NOT NULL CONSTRAINT PK_MOV_ID PRIMARY KEY,
   MVM_CTA_ID INTEGER NOT NULL,
   MVM_FECHA  DATE NOT NULL,
   MVM_MONTO  DECIMAL(20,2) NOT NULL,
   CONSTRAINT FK_MVM_CTA FOREIGN KEY (MVM_CTA_ID)REFERENCES CUENTA(CTA_ID)
);

