--------------------------------------------------------------------------------
-- Creaci�n del Modelo Relacional.
-- Se conecta con el usuario creado para el modelo ER.
--------------------------------------------------------------------------------

-- El usuario que debe estar conectado es: SISECOMMERCE_ER

DROP TABLE ORDEN_COMPRA;
DROP TABLE PRODUCTO;
DROP TABLE CLIENTE;
DROP TABLE TIPO_PRODUCTO;
DROP TABLE TIPO_ENVIO;

commit;

CREATE TABLE TIPO_ENVIO (
   TPE_ID                    INTEGER NOT NULL PRIMARY KEY,
   TPE_DESCRIPCION           VARCHAR(40) NOT NULL,
   TPE_ESTADO                INTEGER NOT NULL,
   TPE_REQUIERE_CONFIRMACION INTEGER
);

CREATE TABLE TIPO_PRODUCTO (
   TPD_ID          INTEGER NOT NULL PRIMARY KEY,
   TPD_DESCRIPCION VARCHAR(40) NOT NULL
);

CREATE TABLE CLIENTE (
   CTE_ID          INTEGER NOT NULL PRIMARY KEY,
   CTE_NOMBRE      VARCHAR(60) NOT NULL
);

CREATE TABLE PRODUCTO (
   PRD_ID INTEGER NOT NULL PRIMARY KEY,
   PRD_TPD_ID INTEGER NOT NULL,
   PRD_NOMBRE VARCHAR(40) NOT NULL,
   PRD_CANTIDAD DECIMAL(10,2) NOT NULL,
   PRD_COSTO_UNITARIO DECIMAL(20,2) NOT NULL,
   FOREIGN KEY (PRD_TPD_ID) REFERENCES TIPO_PRODUCTO(TPD_ID)
);

CREATE TABLE ORDEN_COMPRA (
   OCP_ID INTEGER NOT NULL PRIMARY KEY,
   OCP_PRD_ID INTEGER NOT NULL,
   OCP_CTE_ID INTEGER NOT NULL,
   OCP_TPE_ID INTEGER NOT NULL,
   OCP_FECHA  DATE NOT NULL,
   FOREIGN KEY (OCP_TPE_ID) REFERENCES TIPO_ENVIO(TPE_ID),
   FOREIGN KEY (OCP_PRD_ID) REFERENCES PRODUCTO(PRD_ID),
   FOREIGN KEY (OCP_CTE_ID) REFERENCES CLIENTE(CTE_ID)
);

commit;

