--------------------------------------------------------------------------------
-- Creacion del Modelo Multidimensional.
-- Se conecta con el usuario creado para el modelo DW.
--------------------------------------------------------------------------------


DROP TABLE FACT_ORDENES;        
DROP TABLE DIM_FECHA;     
DROP TABLE DIM_PRODUCTO;
DROP TABLE DIM_CLIENTE;
DROP TABLE DIM_TIPO_PRODUCTO;
DROP TABLE DIM_TIPO_ENVIO;
commit;


CREATE TABLE DIM_TIPO_ENVIO(
   TPE_ID INTEGER NOT NULL CONSTRAINT PK_TPE_ID PRIMARY KEY,
   TPE_DESCRIPCION VARCHAR2(40) NOT NULL
);

CREATE TABLE DIM_TIPO_PRODUCTO(
   TPD_ID INTEGER NOT NULL CONSTRAINT PK_TPD_ID PRIMARY KEY,
   TPD_DESCRIPCION VARCHAR2(40) NOT NULL
);

CREATE TABLE DIM_CLIENTE(
   CTE_ID INTEGER NOT NULL CONSTRAINT PK_CTE_ID PRIMARY KEY,
   CTE_NOMBRE VARCHAR2(60) NOT NULL
);

CREATE TABLE DIM_PRODUCTO(
   PRD_ID INTEGER NOT NULL CONSTRAINT PK_PRD_ID PRIMARY KEY,
   PRD_NOMBRE VARCHAR2(40) NOT NULL
);

CREATE TABLE DIM_FECHA (
   FEC_ID    INTEGER NOT NULL CONSTRAINT PK_FEC_ID PRIMARY KEY,
   FEC_FECHA DATE NOT NULL
);


CREATE TABLE FACT_ORDENES (
   ORD_TPE_ID INTEGER NOT NULL,
   ORD_TPD_ID INTEGER NOT NULL,
   ORD_CTE_ID INTEGER NOT NULL,
   ORD_PRD_ID INTEGER NOT NULL,
   ORD_FEC_ID INTEGER NOT NULL,
   ORD_TPE_ESTADO INTEGER NOT NULL,
   ORD_TPE_REQUIERE_CONFIRMACION INTEGER NOT NULL,
   ORD_PRD_CANTIDAD NUMBER(20,2) NOT NULL,
   ORD_PRD_COSTO_UNITARIO NUMBER(20,2) NOT NULL,
   CONSTRAINT PK_ORD PRIMARY KEY(ORD_TPE_ID, ORD_TPD_ID, ORD_CTE_ID, ORD_PRD_ID, ORD_FEC_ID),
   CONSTRAINT FK_ORD_TPE FOREIGN KEY(ORD_TPE_ID) REFERENCES DIM_TIPO_ENVIO(TPE_ID),
   CONSTRAINT FK_ORD_TPD FOREIGN KEY(ORD_TPD_ID) REFERENCES DIM_TIPO_PRODUCTO(TPD_ID),
   CONSTRAINT FK_ORD_CTE FOREIGN KEY(ORD_CTE_ID) REFERENCES DIM_CLIENTE(CTE_ID),
   CONSTRAINT FK_ORD_PRD FOREIGN KEY(ORD_PRD_ID) REFERENCES DIM_PRODUCTO(PRD_ID),
   CONSTRAINT FK_ORD_FEC FOREIGN KEY(ORD_FEC_ID) REFERENCES DIM_FECHA(FEC_ID)
);


commit;
