--------------------------------------------------------------------------------
-- Creación del Modelo Multidimensional.
-- Se conecta con el usuario creado para el modelo DW.
--------------------------------------------------------------------------------
CREATE TABLE DIM_TIPO_CUENTA (
   TCT_ID          INTEGER NOT NULL CONSTRAINT PK_TCT_ID PRIMARY KEY,
   TCT_DESCRIPCION VARCHAR(30)NOT NULL
);

CREATE TABLE DIM_TIPO_CLIENTE (
   TCL_ID          INTEGER NOT NULL CONSTRAINT PK_TCL_ID PRIMARY KEY,
   TCL_DESCRIPCION VARCHAR(30)NOT NULL
);

CREATE TABLE DIM_ESTADO_CLIENTE (
   ECT_ID          INTEGER NOT NULL CONSTRAINT PK_ECT_ID PRIMARY KEY,
   ECT_DESCRIPCION VARCHAR(30)NOT NULL
);

CREATE TABLE DIM_CUENTA (
   CTA_ID            INTEGER NOT NULL CONSTRAINT PK_CTA_ID PRIMARY KEY,
   CTA_NUMERO_CUENTA VARCHAR(20)NOT NULL
);

CREATE TABLE DIM_FECHA (
   FEC_ID         INTEGER NOT NULL CONSTRAINT PK_FEC_ID PRIMARY KEY,
   FEC_FECHA DATE NOT NULL
);

CREATE TABLE FACT_TRANSACCION (
   TRN_TCL_ID INTEGER NOT NULL,
   TRN_ECT_ID INTEGER NOT NULL,
   TRN_TCT_ID INTEGER NOT NULL,
   TRN_CTE_ID INTEGER NOT NULL,
   TRN_CTA_ID INTEGER NOT NULL,
   TRN_FEC_ID INTEGER NOT NULL,
   TRN_MVM_MONTO NUMBER(20,2) NOT NULL,
   CONSTRAINT PK_TRN PRIMARY KEY(TRN_TCL_ID, TRN_ECT_ID ,TRN_TCT_ID, TRN_CTE_ID, TRN_CTA_ID, TRN_FEC_ID),
   CONSTRAINT FK_TRN_TCL FOREIGN KEY(TRN_TCL_ID) REFERENCES DIM_TIPO_CLIENTE(TCL_ID),
   CONSTRAINT FK_TRN_ECT FOREIGN KEY(TRN_ECT_ID) REFERENCES DIM_ESTADO_CLIENTE(ECT_ID),
   CONSTRAINT FK_TRN_TCT FOREIGN KEY(TRN_TCT_ID) REFERENCES DIM_TIPO_CUENTA(TCT_ID),
   CONSTRAINT FK_TRN_CTA FOREIGN KEY(TRN_CTA_ID) REFERENCES DIM_CUENTA(CTA_ID),
   CONSTRAINT FK_TRN_FEC FOREIGN KEY(TRN_FEC_ID) REFERENCES DIM_FECHA(FEC_ID)
);