-- Tenemos 3 usuarios: 
-- SISECOMMERCE_ER: Modelo Entidad-Relación
-- SISECOMMERCE_SA: Modelo de Transacciones
-- SISECOMMERCE_DW: Modelo de Data Warehouse

-- Tenemos tablas en el modelo ER:
--  ORDEN_COMPRA;
--  PRODUCTO;
--  CLIENTE;
--  TIPO_PRODUCTO;
--  TIPO_ENVIO;


GRANT SELECT ON SISECOMMERCE_ER.ORDEN_COMPRA TO SISECOMMERCE_DW;
GRANT SELECT ON SISECOMMERCE_ER.PRODUCTO TO SISECOMMERCE_DW;
GRANT SELECT ON SISECOMMERCE_ER.CLIENTE TO SISECOMMERCE_DW;
GRANT SELECT ON SISECOMMERCE_ER.TIPO_PRODUCTO TO SISECOMMERCE_DW;
GRANT SELECT ON SISECOMMERCE_ER.TIPO_ENVIO TO SISECOMMERCE_DW;

--------------------------------------------------------------------------------
GRANT SELECT, INSERT ON SISECOMMERCE_SA.SA_ORDEN_COMPRA TO SISECOMMERCE_DW;
GRANT SELECT, INSERT ON SISECOMMERCE_SA.SA_PRODUCTO TO SISECOMMERCE_DW;
GRANT SELECT, INSERT ON SISECOMMERCE_SA.SA_CLIENTE TO SISECOMMERCE_DW;
GRANT SELECT, INSERT ON SISECOMMERCE_SA.SA_TIPO_PRODUCTO TO SISECOMMERCE_DW;
GRANT SELECT, INSERT ON SISECOMMERCE_SA.SA_TIPO_ENVIO TO SISECOMMERCE_DW;

--------------------------------------------------------------------------------

