GRANT SELECT ON SISBANCA_ER.TIPO_CLIENTE TO SISBANCA_DW;
GRANT SELECT ON SISBANCA_ER.CLIENTE TO SISBANCA_DW;
GRANT SELECT ON SISBANCA_ER.CUENTA TO SISBANCA_DW;
GRANT SELECT ON SISBANCA_ER.ESTADO_CLIENTE TO SISBANCA_DW;
GRANT SELECT ON SISBANCA_ER.MOVIMIENTO TO SISBANCA_DW;
GRANT SELECT ON SISBANCA_ER.TIPO_CUENTA TO SISBANCA_DW;
--------------------------------------------------------------------------------
GRANT SELECT, INSERT ON SISBANCA_SA.SA_TIPO_CLIENTE TO SISBANCA_DW;
GRANT SELECT, INSERT ON SISBANCA_SA.SA_TIPO_CUENTA TO SISBANCA_DW;
GRANT SELECT, INSERT ON SISBANCA_SA.SA_ESTADO_CLIENTE TO SISBANCA_DW;
GRANT SELECT, INSERT ON SISBANCA_SA.SA_CUENTA TO SISBANCA_DW;
GRANT SELECT, INSERT ON SISBANCA_SA.SA_CLIENTE TO SISBANCA_DW;
GRANT SELECT, INSERT ON SISBANCA_SA.SA_MOVIMIENTO TO SISBANCA_DW;
--------------------------------------------------------------------------------
