--------------------------------------------------------------------------------
-- ETL DEL SA
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PG_ETL_SA AS
   PROCEDURE CARGA_TIPO_CUENTA;
   PROCEDURE CARGA_TIPO_CLIENTE;
   PROCEDURE CARGA_DATOS;
END PG_ETL_SA;
/

CREATE OR REPLACE PACKAGE BODY PG_ETL_SA AS
   PROCEDURE CARGA_TIPO_CUENTA AS
   BEGIN
      INSERT INTO SISBANCA_SA.SA_TIPO_CUENTA(TCT_ID, TCT_DESCRIPCION)
      SELECT TCT_ID, TCT_DESCRIPCION
        FROM SISBANCA_ER.TIPO_CUENTA
       WHERE TCT_ID NOT IN (SELECT TCT_ID FROM SISBANCA_SA.SA_TIPO_CUENTA);
   END CARGA_TIPO_CUENTA;
   PROCEDURE CARGA_TIPO_CLIENTE AS
   BEGIN
      INSERT INTO SISBANCA_SA.SA_TIPO_CLIENTE(TCL_ID, TCL_DESCRIPCION)
      SELECT TCL_ID, TCL_DESCRIPCION
        FROM SISBANCA_ER.TIPO_CLIENTE
       WHERE TCL_ID NOT IN (SELECT TCL_ID FROM SISBANCA_SA.SA_TIPO_CLIENTE);
   END CARGA_TIPO_CLIENTE;
   PROCEDURE CARGA_DATOS AS
   BEGIN
     CARGA_TIPO_CUENTA;
     CARGA_TIPO_CLIENTE;
   END CARGA_DATOS;
END PG_ETL_SA;
/

EXECUTE PG_ETL_SA.CARGA_DATOS;