--------------------------------------------------------------------------------
-- ETL DEL SA
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PG_ETL_SA AS
   procedure CARGA_TIPO_PRODUCTO;
   -- PROCEDURE CARGA_TIPO_CUENTA;
   -- PROCEDURE CARGA_TIPO_CLIENTE;
   PROCEDURE CARGA_DATOS;
END PG_ETL_SA;
/

CREATE OR REPLACE PACKAGE BODY PG_ETL_SA AS
   PROCEDURE CARGA_TIPO_PRODUCTO AS
   BEGIN
      INSERT INTO SISECOMMERCE_SA.SA_TIPO_PRODUCTO(TPD_ID, TPD_DESCRIPCION)
      SELECT TPD_ID, TPD_DESCRIPCION
        FROM SISECOMMERCE_ER.TIPO_PRODUCTO
       WHERE TPD_ID NOT IN (SELECT TPD_ID FROM SISECOMMERCE_SA.SA_TIPO_PRODUCTO);
   END CARGA_TIPO_PRODUCTO;
   -- PROCEDURE CARGA_TIPO_CUENTA AS
   -- BEGIN
   --    INSERT INTO SISBANCA_SA.SA_TIPO_CUENTA(TCT_ID, TCT_DESCRIPCION)
   --    SELECT TCT_ID, TCT_DESCRIPCION
   --      FROM SISBANCA_ER.TIPO_CUENTA
   --     WHERE TCT_ID NOT IN (SELECT TCT_ID FROM SISBANCA_SA.SA_TIPO_CUENTA);
   -- END CARGA_TIPO_CUENTA;
   -- PROCEDURE CARGA_TIPO_CLIENTE AS
   -- BEGIN
   --    INSERT INTO SISBANCA_SA.SA_TIPO_CLIENTE(TCL_ID, TCL_DESCRIPCION)
   --    SELECT TCL_ID, TCL_DESCRIPCION
   --      FROM SISBANCA_ER.TIPO_CLIENTE
   --     WHERE TCL_ID NOT IN (SELECT TCL_ID FROM SISBANCA_SA.SA_TIPO_CLIENTE);
   -- END CARGA_TIPO_CLIENTE;
   PROCEDURE CARGA_DATOS AS
   BEGIN
     CARGA_TIPO_PRODUCTO;
   --   CARGA_TIPO_CUENTA;
   --   CARGA_TIPO_CLIENTE;
   COMMIT;
   END CARGA_DATOS;
END PG_ETL_SA;
/

EXECUTE PG_ETL_SA.CARGA_DATOS;

-- Selects para validar que hayan datos
SELECT * FROM SISECOMMERCE_SA.SA_TIPO_PRODUCTO;
