--------------------------------------------------------------------------------
-- ETL DEL SA
--------------------------------------------------------------------------------

-- El usuario que debe estar conectado es: SISECOMMERCE_DW

CREATE OR REPLACE PACKAGE PG_ETL_SA AS
   procedure CARGA_TIPO_PRODUCTO;
   procedure CARGA_TIPO_ENVIO;
   procedure CARGA_CLIENTE;
   procedure CARGA_PRODUCTO;
   procedure CARGA_ORDEN_COMPRA;
   procedure CARGA_DATOS;
END PG_ETL_SA;
/

CREATE OR REPLACE PACKAGE BODY PG_ETL_SA AS
   PROCEDURE CARGA_TIPO_PRODUCTO AS
   BEGIN
      INSERT INTO SISECOMMERCE_SA.SA_TIPO_PRODUCTO(TPD_ID, TPD_DESCRIPCION)
      SELECT TPD_ID, TPD_DESCRIPCION
        FROM SISECOMMERCE_ER.TIPO_PRODUCTO
       WHERE TPD_ID NOT IN (SELECT TPD_ID FROM SISECOMMERCE_SA.SA_TIPO_PRODUCTO);
   END CARGA_TIPO_PRODUCTO;
   PROCEDURE CARGA_TIPO_ENVIO AS
   BEGIN
      INSERT INTO SISECOMMERCE_SA.SA_TIPO_ENVIO(TPE_ID, TPE_DESCRIPCION, TPE_ESTADO, TPE_REQUIERE_CONFIRMACION)
      SELECT TPE_ID, TPE_DESCRIPCION, TPE_ESTADO, TPE_REQUIERE_CONFIRMACION
        FROM SISECOMMERCE_ER.TIPO_ENVIO
       WHERE TPE_ID NOT IN (SELECT TPE_ID FROM SISECOMMERCE_SA.SA_TIPO_ENVIO);
   END CARGA_TIPO_ENVIO;
   PROCEDURE CARGA_CLIENTE AS
   BEGIN
      INSERT INTO SISECOMMERCE_SA.SA_CLIENTE(CTE_ID, CTE_NOMBRE)
      SELECT CTE_ID, CTE_NOMBRE
        FROM SISECOMMERCE_ER.CLIENTE
       WHERE CTE_ID NOT IN (SELECT CTE_ID FROM SISECOMMERCE_SA.SA_CLIENTE);
   END CARGA_CLIENTE;
   PROCEDURE CARGA_PRODUCTO AS
   BEGIN
      INSERT INTO SISECOMMERCE_SA.SA_PRODUCTO(PRD_ID, PRD_TPD_ID, PRD_NOMBRE, PRD_CANTIDAD, PRD_COSTO_UNITARIO)
      SELECT PRD_ID, PRD_TPD_ID, PRD_NOMBRE, PRD_CANTIDAD, PRD_COSTO_UNITARIO
        FROM SISECOMMERCE_ER.PRODUCTO
       WHERE PRD_ID NOT IN (SELECT PRD_ID FROM SISECOMMERCE_SA.SA_PRODUCTO);
   END CARGA_PRODUCTO;
   PROCEDURE CARGA_ORDEN_COMPRA AS
   BEGIN
      INSERT INTO SISECOMMERCE_SA.SA_ORDEN_COMPRA(OCP_ID, OCP_PRD_ID, OCP_CTE_ID, OCP_TPE_ID, OCP_FECHA)
      SELECT OCP_ID, OCP_PRD_ID, OCP_CTE_ID, OCP_TPE_ID, OCP_FECHA
        FROM SISECOMMERCE_ER.ORDEN_COMPRA
       WHERE OCP_ID NOT IN (SELECT OCP_ID FROM SISECOMMERCE_SA.SA_ORDEN_COMPRA);
   END CARGA_ORDEN_COMPRA;
   PROCEDURE CARGA_DATOS AS
   BEGIN
     CARGA_TIPO_PRODUCTO;
     CARGA_TIPO_ENVIO;
     CARGA_CLIENTE;
     CARGA_PRODUCTO;
     CARGA_ORDEN_COMPRA;
   COMMIT;
   END CARGA_DATOS;
END PG_ETL_SA;
/

EXECUTE PG_ETL_SA.CARGA_DATOS;

-- Selects para validar que hayan datos
SELECT * FROM SISECOMMERCE_SA.SA_TIPO_PRODUCTO;
SELECT * FROM SISECOMMERCE_SA.SA_TIPO_ENVIO;
SELECT * FROM SISECOMMERCE_SA.SA_CLIENTE;
SELECT * FROM SISECOMMERCE_SA.SA_PRODUCTO;
SELECT * FROM SISECOMMERCE_SA.SA_ORDEN_COMPRA;
